version: '3'

services:
  # ROS CAN 매니저 서비스 설정
  ros-canmanager:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros-canmanager:latest
    container_name: ros-canmanager-container
    ports:
      - "2223:2222"
    restart: unless-stopped
    privileged: true  # CAN 장치 접근을 위한 권한 부여
    volumes:
      - ./workspace:/workspace  # 작업 디렉토리 마운트